"""Change table names to UserRole and TaskStatus

Revision ID: 25be0aa8ccea
Revises: b571c4d4b8cd
Create Date: 2020-10-26 20:15:30.485724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25be0aa8ccea'
down_revision = 'b571c4d4b8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_status'))
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_status_status', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_status_task_status'), 'task_status', ['status'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_role_role', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_role_user_role'), 'user_role', ['role'], ['id'], ondelete='CASCADE')
    op.drop_table('role')
    op.drop_table('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_role_user_role'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_role_role', 'role', ['role'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_status_task_status'), type_='foreignkey')
        batch_op.create_foreign_key('fk_task_status_status', 'status', ['status'], ['id'], ondelete='CASCADE')

    op.create_table('status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_status')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_role')
    )
    op.drop_table('user_role')
    op.drop_table('task_status')
    # ### end Alembic commands ###
