"""empty message

Revision ID: 26985f0eb0b9
Revises: e907c31e3ad4
Create Date: 2020-10-28 13:47:49.564472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26985f0eb0b9'
down_revision = 'e907c31e3ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancers_responded', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'freelancers_responded', type_='foreignkey')
    op.create_foreign_key(None, 'freelancers_responded', 'user', ['user_id'], ['id'])
    op.drop_column('freelancers_responded', 'freelancers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancers_responded', sa.Column('freelancers_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'freelancers_responded', type_='foreignkey')
    op.create_foreign_key(None, 'freelancers_responded', 'user', ['freelancers_id'], ['id'])
    op.drop_column('freelancers_responded', 'user_id')
    # ### end Alembic commands ###
