"""Adjust to new model m2m

Revision ID: 359529d49d8a
Revises: 25be0aa8ccea
Create Date: 2020-10-28 20:15:24.629016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359529d49d8a'
down_revision = '25be0aa8ccea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancers_who_responded',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_freelancers_who_responded_task_id_task')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_freelancers_who_responded_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freelancers_who_responded')
    # ### end Alembic commands ###
