"""Change Task_status 

Revision ID: 9586aa8f2127
Revises: 80909fd34502
Create Date: 2020-10-01 02:02:45.449022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9586aa8f2127'
down_revision = '80909fd34502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email', ['email'])
    op.drop_column('email', 'email_value')
    op.add_column('phone', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'phone', ['phone'])
    op.drop_column('phone', 'phone_value')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.add_column('task', sa.Column('customer', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('freelancer', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('tag', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task_status', ['status'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'user', ['tag'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'user', ['freelancer'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'user', ['customer'], ['id'], ondelete='CASCADE')
    op.drop_column('task', 'finish_role')
    op.drop_column('task', 'finish_tag')
    op.add_column('task_status', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('task_status', 'task_value')
    op.add_column('user', sa.Column('public_bio', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'email', ['email'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'user', ['tag'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'user_role', ['role'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'phone', ['phone'], ['id'], ondelete='CASCADE')
    op.add_column('user_role', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('user_role', 'role_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('role_value', sa.VARCHAR(), nullable=False))
    op.drop_column('user_role', 'role')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'public_bio')
    op.add_column('task_status', sa.Column('task_value', sa.VARCHAR(), nullable=False))
    op.drop_column('task_status', 'status')
    op.add_column('task', sa.Column('finish_tag', sa.VARCHAR(), nullable=True))
    op.add_column('task', sa.Column('finish_role', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'tag')
    op.drop_column('task', 'freelancer')
    op.drop_column('task', 'customer')
    op.create_foreign_key(None, 'tag', 'user', ['tag'], ['tag'], ondelete='CASCADE')
    op.add_column('phone', sa.Column('phone_value', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'phone', type_='unique')
    op.drop_column('phone', 'phone')
    op.add_column('email', sa.Column('email_value', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'email', type_='unique')
    # ### end Alembic commands ###
