"""Поправил связи

Revision ID: 9bd957561eee
Revises: 8092d3e20977
Create Date: 2020-09-29 17:21:57.768712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd957561eee'
down_revision = '8092d3e20977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'email', ['email'])
    op.drop_column('email', 'email_value')
    op.add_column('phone', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'phone', ['phone'])
    op.drop_column('phone', 'phone_value')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'user', ['tag'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'tag', ['finish_tag'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'user', ['finish_role'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'task_status', ['status'], ['id'], ondelete='CASCADE')
    op.add_column('task_status', sa.Column('task', sa.String(), nullable=False))
    op.drop_column('task_status', 'task_value')
    op.create_foreign_key(None, 'user', 'user_role', ['role'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'phone', ['phone'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'email', ['email'], ['id'], ondelete='CASCADE')
    op.add_column('user_role', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('user_role', 'role_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('role_value', sa.VARCHAR(), nullable=False))
    op.drop_column('user_role', 'role')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('task_status', sa.Column('task_value', sa.VARCHAR(), nullable=False))
    op.drop_column('task_status', 'task')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'user', ['tag'], ['tag'], ondelete='CASCADE')
    op.add_column('phone', sa.Column('phone_value', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'phone', type_='unique')
    op.drop_column('phone', 'phone')
    op.add_column('email', sa.Column('email_value', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'email', type_='unique')
    op.drop_column('email', 'email')
    # ### end Alembic commands ###
