"""Поменял username на user_name

Revision ID: ac9e7151b620
Revises: 359529d49d8a
Create Date: 2020-11-02 15:14:07.535357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9e7151b620'
down_revision = '359529d49d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_user_name'), ['user_name'], unique=True)
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('username')

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_index(batch_op.f('ix_user_user_name'))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
