"""empty message

Revision ID: e907c31e3ad4
Revises: fde4439a2dc9
Create Date: 2020-10-26 23:44:09.429909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e907c31e3ad4'
down_revision = 'fde4439a2dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancers_responded',
    sa.Column('freelancers_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['freelancers_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    op.drop_table('freelancers_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancers_tasks',
    sa.Column('freelancers_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['freelancers_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('freelancers_id', 'task_id')
    )
    op.drop_table('freelancers_responded')
    # ### end Alembic commands ###
